/**
  ******************************************************************************
  * @file    ethernetif.c
  * @brief   lwIP network interface driver on top of the STM32N6 ETH HAL driver
  ******************************************************************************
  * Adapted from STMicroelectronics' stm32n6-classic-coremw-apps reference
  * (Projects/NUCLEO-N657X0-Q/Applications/LwIP/LwIP_UDP_Echo_Server/LwIP/Target
  * /ethernetif.c) for the BlindFold project.
  *
  * Differences vs. the ST reference:
  *  - heth1 / TxConfig / DMARxDscrTab / DMATxDscrTab are NOT redeclared here.
  *    They already exist as globals generated by CubeMX in main.c (MX_ETH1_Init),
  *    which also already calls HAL_ETH_Init(). This file only adds the lwIP
  *    zero-copy RX pool and the PHY bring-up on top of that existing init.
  *  - HAL_ETH_MspInit/MspDeInit are NOT here either -- CubeMX already generated
  *    them in stm32n6xx_hal_msp.c for this board's actual RMII pinout.
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "lwip/opt.h"
#include "lwip/timeouts.h"
#include "lwip/netif.h"
#include "netif/etharp.h"
#include "ethernetif.h"
#include "lan8742.h"
#include "net_display.h"
#include <string.h>
#include <stdio.h>

/* Private define ------------------------------------------------------------*/
/* Network interface name */
#define IFNAME0 'b'
#define IFNAME1 'f'

#define ETH_DMA_TRANSMIT_TIMEOUT      (20U)

/* Must match heth1.Init.RxBuffLen set in MX_ETH1_Init() (main.c) */
#define ETH_RX_BUFFER_SIZE            1536U
#define ETH_RX_BUFFER_CNT             12U

/* Private typedef -------------------------------------------------------- */
/*
@Note: This interface operates in zero-copy mode for RX only:
        - Rx buffers are allocated from the lwIP RX_POOL below, then handed
          to the ETH HAL driver directly (no memcpy).
        - Tx buffers come straight from whatever pbuf lwIP/the app already
          built; low_level_output() just points DMA at them.
*/
typedef enum
{
  RX_ALLOC_OK       = 0x00,
  RX_ALLOC_ERROR    = 0x01
} RxAllocStatusTypeDef;

typedef struct
{
  struct pbuf_custom pbuf_custom;
  uint8_t buff[(ETH_RX_BUFFER_SIZE + 31) & ~31] __ALIGNED(32);
} RxBuff_t;

/* Zero-copy RX pbuf pool */
LWIP_MEMPOOL_DECLARE(RX_POOL, ETH_RX_BUFFER_CNT, sizeof(RxBuff_t), "Zero-copy RX PBUF pool");

/* Private variables ---------------------------------------------------------*/
static uint8_t RxAllocStatus;

/* Private function prototypes -----------------------------------------------*/
u32_t sys_now(void);

int32_t ETH_PHY_IO_Init(void);
int32_t ETH_PHY_IO_DeInit(void);
int32_t ETH_PHY_IO_ReadReg(uint32_t DevAddr, uint32_t RegAddr, uint32_t *pRegVal);
int32_t ETH_PHY_IO_WriteReg(uint32_t DevAddr, uint32_t RegAddr, uint32_t RegVal);
int32_t ETH_PHY_IO_GetTick(void);

lan8742_Object_t LAN8742;
lan8742_IOCtx_t  LAN8742_IOCtx = {ETH_PHY_IO_Init,
                                   ETH_PHY_IO_DeInit,
                                   ETH_PHY_IO_WriteReg,
                                   ETH_PHY_IO_ReadReg,
                                   ETH_PHY_IO_GetTick
                                  };

/* Private functions ---------------------------------------------------------*/
void pbuf_free_custom(struct pbuf *p);

/*******************************************************************************
                       LL Driver Interface ( LwIP stack --> ETH)
*******************************************************************************/
/**
  * @brief In this function, the hardware should be initialized.
  * Called from ethernetif_init().
  *
  * heth1 has already been fully brought up by MX_ETH1_Init() (main.c) before
  * this runs -- instance, MAC address, DMA descriptor tables, RxBuffLen and
  * TxConfig are all set there. This function only layers lwIP's RX pool and
  * the PHY driver on top.
  */
static void low_level_init(struct netif *netif)
{
  /* set MAC hardware address length */
  netif->hwaddr_len = ETH_HWADDR_LEN;

  /* set MAC hardware address, taken from what MX_ETH1_Init() already
   * configured on heth1 -- single source of truth, no risk of divergence */
  memcpy(netif->hwaddr, heth1.Init.MACAddr, ETH_HWADDR_LEN);

  /* maximum transfer unit */
  netif->mtu = ETH_MAX_PAYLOAD;

  /* device capabilities */
  /* don't set NETIF_FLAG_ETHARP if this device is not an ethernet one */
  netif->flags |= NETIF_FLAG_BROADCAST | NETIF_FLAG_ETHARP;

  /* Initialize the RX POOL */
  LWIP_MEMPOOL_INIT(RX_POOL);

  /* Set PHY IO functions */
  LAN8742_RegisterBusIO(&LAN8742, &LAN8742_IOCtx);

  /* Initialize the LAN8742 ETH PHY */
  if (LAN8742_Init(&LAN8742) != LAN8742_STATUS_OK)
  {
    netif_set_link_down(netif);
    netif_set_down(netif);
    return;
  }

  ethernet_link_check_state(netif);
}

/**
  * @brief This function should do the actual transmission of the packet. The packet is
  * contained in the pbuf that is passed to the function. This pbuf
  * might be chained.
  *
  * @param netif the lwip network interface structure for this ethernetif
  * @param p the MAC packet to send (e.g. IP packet including MAC addresses and type)
  * @return ERR_OK if the packet could be sent
  *         an err_t value if the packet couldn't be sent
  */
static err_t low_level_output(struct netif *netif, struct pbuf *p)
{
  uint32_t i = 0U;
  struct pbuf *q = NULL;
  err_t errval = ERR_OK;
  ETH_BufferTypeDef Txbuffer[ETH_TX_DESC_CNT] = {0};

  LWIP_UNUSED_ARG(netif);

  memset(Txbuffer, 0, ETH_TX_DESC_CNT * sizeof(ETH_BufferTypeDef));

  for (q = p; q != NULL; q = q->next)
  {
    if (i >= ETH_TX_DESC_CNT)
    {
      return ERR_IF;
    }

    Txbuffer[i].buffer = q->payload;
    Txbuffer[i].len = q->len;

    if (i > 0)
    {
      Txbuffer[i - 1].next = &Txbuffer[i];
    }

    if (q->next == NULL)
    {
      Txbuffer[i].next = NULL;
    }

    i++;
  }

  TxConfig.Length = p->tot_len;
  TxConfig.TxBuffer = Txbuffer;
  TxConfig.pData = p;

  if (HAL_ETH_Transmit(&heth1, &TxConfig, ETH_DMA_TRANSMIT_TIMEOUT) == HAL_OK)
  {
    errval = ERR_OK;
  }
  else
  {
    errval = ERR_IF;
  }

  return errval;
}

/**
  * @brief Should allocate a pbuf and transfer the bytes of the incoming
  * packet from the interface into the pbuf.
  */
static struct pbuf *low_level_input(struct netif *netif)
{
  struct pbuf *p = NULL;

  LWIP_UNUSED_ARG(netif);

  if (RxAllocStatus == RX_ALLOC_OK)
  {
    HAL_ETH_ReadData(&heth1, (void **)&p);
  }
  return p;
}

/**
  * @brief This function is the ethernetif_input task, it is processed when a packet
  * is ready to be read from the interface. Call this often from the main loop
  * (this project runs lwIP in NO_SYS / polling mode, no RTOS task for it).
  */
void ethernetif_input(struct netif *netif)
{
  struct pbuf *p = NULL;

  do
  {
    p = low_level_input(netif);
    if (p != NULL)
    {
      if (netif->input(p, netif) != ERR_OK)
      {
        pbuf_free(p);
      }
    }
  } while (p != NULL);
}

/**
  * @brief Should be called at the beginning of the program to set up the
  * network interface. Pass this to netif_add().
  */
err_t ethernetif_init(struct netif *netif)
{
  LWIP_ASSERT("netif != NULL", (netif != NULL));

#if LWIP_NETIF_HOSTNAME
  netif->hostname = "blindfold";
#endif /* LWIP_NETIF_HOSTNAME */

  netif->name[0] = IFNAME0;
  netif->name[1] = IFNAME1;
  netif->output = etharp_output;
  netif->linkoutput = low_level_output;

  low_level_init(netif);

  return ERR_OK;
}

/**
  * @brief  Custom Rx pbuf free callback
  */
void pbuf_free_custom(struct pbuf *p)
{
  struct pbuf_custom *custom_pbuf = (struct pbuf_custom *)p;
  LWIP_MEMPOOL_FREE(RX_POOL, custom_pbuf);

  if (RxAllocStatus == RX_ALLOC_ERROR)
  {
    RxAllocStatus = RX_ALLOC_OK;
  }
}

/**
  * @brief  Returns the current time in milliseconds
  *         when LWIP_TIMERS == 1 and NO_SYS == 1
  */
u32_t sys_now(void)
{
  return HAL_GetTick();
}

/*******************************************************************************
                       PHY IO Functions
*******************************************************************************/
/**
  * @brief  Initializes the MDIO interface GPIO and clocks.
  *         GPIO config itself is already done in HAL_ETH_MspInit() (CubeMX
  *         generated, stm32n6xx_hal_msp.c) -- this just sets the MDIO clock.
  */
int32_t ETH_PHY_IO_Init(void)
{
  HAL_ETH_SetMDIOClockRange(&heth1);
  return 0;
}

int32_t ETH_PHY_IO_DeInit(void)
{
  return 0;
}

int32_t ETH_PHY_IO_ReadReg(uint32_t DevAddr, uint32_t RegAddr, uint32_t *pRegVal)
{
  if (HAL_ETH_ReadPHYRegister(&heth1, DevAddr, RegAddr, pRegVal) != HAL_OK)
  {
    return -1;
  }
  return 0;
}

int32_t ETH_PHY_IO_WriteReg(uint32_t DevAddr, uint32_t RegAddr, uint32_t RegVal)
{
  if (HAL_ETH_WritePHYRegister(&heth1, DevAddr, RegAddr, RegVal) != HAL_OK)
  {
    return -1;
  }
  return 0;
}

int32_t ETH_PHY_IO_GetTick(void)
{
  return HAL_GetTick();
}

/**
  * @brief  Check whether the LAN8742 is actually answering on MDIO.
  *         A non-responding PHY (unpowered, still in reset, wrong
  *         address, or nobody driving the bus) reads back all-1s --
  *         BSR == 0xFFFF. LAN8742_GetLinkState() has no way to tell that
  *         apart from a real response: LINK_STATUS, AUTONEGO_EN and
  *         AUTONEGO_DONE are all "set" when every bit is 1, so it
  *         decodes straight through to a false LAN8742_STATUS_10MBITS_
  *         HALFDUPLEX instead of an error. Call this first and only
  *         trust GetLinkState()'s result if it returns 1.
  * @retval 1 if the PHY answered with something other than the all-1s
  *         pattern, 0 if it didn't (or the MDIO read itself failed).
  */
static uint8_t ethernet_phy_is_responding(void)
{
  uint32_t bsr = 0;

  if (ETH_PHY_IO_ReadReg(LAN8742.DevAddr, LAN8742_BSR, &bsr) < 0)
  {
    return 0U;
  }

  return ((bsr & 0xFFFFU) != 0xFFFFU) ? 1U : 0U;
}

/**
  * @brief  Poll the PHY link state and (re)start/stop the MAC/DMA to match.
  *         Called from Ethernet_Link_Periodic_Handle() (app_ethernet.c).
  */
void ethernet_link_check_state(struct netif *netif)
{
  ETH_MACConfigTypeDef MACConf = {0};
  int32_t PHYLinkState = 0;
  uint32_t linkchanged = 0U, speed = 0U, duplex = 0U;

  /* Guard against the non-responding-PHY false-positive described above --
   * without this, PHYLinkState can never come back LINK_DOWN/error, so a
   * netif that's ever gone "up" can never come back down. */
  PHYLinkState = ethernet_phy_is_responding() ? LAN8742_GetLinkState(&LAN8742)
                                               : LAN8742_STATUS_READ_ERROR;

  if (netif_is_link_up(netif) && (PHYLinkState <= LAN8742_STATUS_LINK_DOWN))
  {
    HAL_ETH_Stop(&heth1);
    netif_set_down(netif);
    netif_set_link_down(netif);
  }
  else if (!netif_is_link_up(netif) && (PHYLinkState > LAN8742_STATUS_LINK_DOWN))
  {
    switch (PHYLinkState)
    {
      case LAN8742_STATUS_100MBITS_FULLDUPLEX:
        duplex = ETH_FULLDUPLEX_MODE;
        speed = ETH_SPEED_100M;
        linkchanged = 1;
        break;
      case LAN8742_STATUS_100MBITS_HALFDUPLEX:
        duplex = ETH_HALFDUPLEX_MODE;
        speed = ETH_SPEED_100M;
        linkchanged = 1;
        break;
      case LAN8742_STATUS_10MBITS_FULLDUPLEX:
        duplex = ETH_FULLDUPLEX_MODE;
        speed = ETH_SPEED_10M;
        linkchanged = 1;
        break;
      case LAN8742_STATUS_10MBITS_HALFDUPLEX:
        duplex = ETH_HALFDUPLEX_MODE;
        speed = ETH_SPEED_10M;
        linkchanged = 1;
        break;
      default:
        break;
    }

    if (linkchanged)
    {
      HAL_ETH_GetMACConfig(&heth1, &MACConf);
      MACConf.DuplexMode = duplex;
      MACConf.Speed = speed;
      HAL_ETH_SetMACConfig(&heth1, &MACConf);
      HAL_ETH_Start(&heth1);
      netif_set_up(netif);
      netif_set_link_up(netif);
    }
  }
}

/**
  * @brief  Show a human-readable LAN connection status on the OLED debug
  *         row (y=40). Was originally a raw PHY-register dump used to
  *         chase a "link up while unplugged" bug; root cause was a
  *         non-responding PHY decoding as a false link-up (see
  *         ethernet_phy_is_responding()). Now shows:
  *           - "LAN:NO RESP xxxx" if the PHY isn't answering on MDIO at
  *             all (xxxx is the raw BSR read, kept for reference -- it
  *             should stop reading FFFF once the non-response is fixed)
  *           - "LAN:DOWN" / "LAN:NEGOTIATING" if the PHY responds but
  *             reports no cable / autonegotiation still in progress
  *           - "LAN:UP <speed>-<duplex>" if the link is genuinely up
  *         Call periodically from the main loop (e.g. every 200-300ms).
  */
void ethernet_phy_debug_print(void)
{
  char line[17];

  if (!ethernet_phy_is_responding())
  {
    uint32_t bsr = 0;
    (void)ETH_PHY_IO_ReadReg(LAN8742.DevAddr, LAN8742_BSR, &bsr);
    snprintf(line, sizeof(line), "LAN:NO RESP %04lX", (unsigned long)(bsr & 0xFFFFU));
  }
  else
  {
    int32_t phy_status = LAN8742_GetLinkState(&LAN8742);

    switch (phy_status)
    {
      case LAN8742_STATUS_100MBITS_FULLDUPLEX:
        snprintf(line, sizeof(line), "LAN:UP 100M-FD");
        break;
      case LAN8742_STATUS_100MBITS_HALFDUPLEX:
        snprintf(line, sizeof(line), "LAN:UP 100M-HD");
        break;
      case LAN8742_STATUS_10MBITS_FULLDUPLEX:
        snprintf(line, sizeof(line), "LAN:UP 10M-FD");
        break;
      case LAN8742_STATUS_10MBITS_HALFDUPLEX:
        snprintf(line, sizeof(line), "LAN:UP 10M-HD");
        break;
      case LAN8742_STATUS_LINK_DOWN:
        snprintf(line, sizeof(line), "LAN:DOWN");
        break;
      case LAN8742_STATUS_AUTONEGO_NOTDONE:
        snprintf(line, sizeof(line), "LAN:NEGOTIATING");
        break;
      default:
        snprintf(line, sizeof(line), "LAN:ERR %ld", (long)phy_status);
        break;
    }
  }

  NetDisplay_ShowDebug(line);
}

/*******************************************************************************
                       HAL_ETH zero-copy RX callbacks
*******************************************************************************/
void HAL_ETH_RxAllocateCallback(uint8_t **buff)
{
  struct pbuf_custom *p = LWIP_MEMPOOL_ALLOC(RX_POOL);
  if (p)
  {
    *buff = (uint8_t *)p + offsetof(RxBuff_t, buff);
    p->custom_free_function = pbuf_free_custom;
    pbuf_alloced_custom(PBUF_RAW, 0, PBUF_REF, p, *buff, ETH_RX_BUFFER_SIZE);
  }
  else
  {
    RxAllocStatus = RX_ALLOC_ERROR;
    *buff = NULL;
  }
}

void HAL_ETH_RxLinkCallback(void **pStart, void **pEnd, uint8_t *buff, uint16_t Length)
{
  struct pbuf **ppStart = (struct pbuf **)pStart;
  struct pbuf **ppEnd = (struct pbuf **)pEnd;
  struct pbuf *p = NULL;

  p = (struct pbuf *)(buff - offsetof(RxBuff_t, buff));
  p->next = NULL;
  p->tot_len = 0;
  p->len = Length;

  if (!*ppStart)
  {
    *ppStart = p;
  }
  else
  {
    (*ppEnd)->next = p;
  }
  *ppEnd = p;

  for (p = *ppStart; p != NULL; p = p->next)
  {
    p->tot_len += Length;
  }
}

void HAL_ETH_TxFreeCallback(uint32_t *buff)
{
  pbuf_free((struct pbuf *)buff);
}
